### ISSUE TITLE
REDIS_URL required

### ISSUE THREAD

**Issue by ludovicc** [chop-dbhi/biorepo-portal#8]
Hello,

I tried to run 'docker-compose up brp', but it fails with the following error:

````
Starting biorepoportal_memcached_1
Starting biorepoportal_ehb_1
Starting biorepoportal_brp_1
Attaching to biorepoportal_brp_1
brp_1 | Traceback (most recent call last):
brp_1 |   File "./bin/manage.py", line 20, in <module>
brp_1 |     execute_from_command_line()
brp_1 |   File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 399, in execute_from_command_line
brp_1 |     utility.execute()
brp_1 |   File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 392, in execute
brp_1 |     self.fetch_command(subcommand).run_from_argv(self.argv)
brp_1 |   File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 272, in fetch_command
brp_1 |     klass = load_command_class(app_name, subcommand)
brp_1 |   File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 75, in load_command_class
brp_1 |     module = import_module('%s.management.commands.%s' % (app_name, name))
brp_1 |   File "/usr/local/lib/python2.7/site-packages/django/utils/importlib.py", line 40, in import_module
brp_1 |     __import__(name)
brp_1 |   File "/usr/local/lib/python2.7/site-packages/django/core/management/commands/syncdb.py", line 9, in <module>
brp_1 |     from django.core.management.sql import custom_sql_for_model, emit_post_sync_signal, emit_pre_sync_signal
brp_1 |   File "/usr/local/lib/python2.7/site-packages/django/core/management/sql.py", line 9, in <module>
brp_1 |     from django.db import models
brp_1 |   File "/usr/local/lib/python2.7/site-packages/django/db/models/__init__.py", line 5, in <module>
brp_1 |     from django.db.models.query import Q
brp_1 |   File "/usr/local/lib/python2.7/site-packages/django/db/models/query.py", line 17, in <module>
brp_1 |     from django.db.models.deletion import Collector
brp_1 |   File "/usr/local/lib/python2.7/site-packages/django/db/models/deletion.py", line 4, in <module>
brp_1 |     from django.db.models import signals, sql
brp_1 |   File "/usr/local/lib/python2.7/site-packages/django/db/models/sql/__init__.py", line 4, in <module>
brp_1 |     from django.db.models.sql.subqueries import *
brp_1 |   File "/usr/local/lib/python2.7/site-packages/django/db/models/sql/subqueries.py", line 12, in <module>
brp_1 |     from django.db.models.sql.query import Query
brp_1 |   File "/usr/local/lib/python2.7/site-packages/django/db/models/sql/query.py", line 22, in <module>
brp_1 |     from django.db.models.sql import aggregates as base_aggregates_module
brp_1 |   File "/usr/local/lib/python2.7/site-packages/django/db/models/sql/aggregates.py", line 9, in <module>
brp_1 |     ordinal_aggregate_field = IntegerField()
brp_1 |   File "/usr/local/lib/python2.7/site-packages/django/db/models/fields/__init__.py", line 116, in __init__
brp_1 |     self.db_tablespace = db_tablespace or settings.DEFAULT_INDEX_TABLESPACE
brp_1 |   File "/usr/local/lib/python2.7/site-packages/django/conf/__init__.py", line 54, in __getattr__
brp_1 |     self._setup(name)
brp_1 |   File "/usr/local/lib/python2.7/site-packages/django/conf/__init__.py", line 49, in _setup
brp_1 |     self._wrapped = Settings(settings_module)
brp_1 |   File "/usr/local/lib/python2.7/site-packages/django/conf/__init__.py", line 128, in __init__
brp_1 |     mod = importlib.import_module(self.SETTINGS_MODULE)
brp_1 |   File "/usr/local/lib/python2.7/site-packages/django/utils/importlib.py", line 40, in import_module
brp_1 |     __import__(name)
brp_1 |   File "/opt/app/brp/conf/settings.py", line 25, in <module>
brp_1 |     'redis': env.cache('REDIS_URL')
brp_1 |   File "/usr/local/lib/python2.7/site-packages/environ/environ.py", line 188, in cache_url
brp_1 |     return self.cache_url_config(self.url(var, default=default), backend=backend)
brp_1 |   File "/usr/local/lib/python2.7/site-packages/environ/environ.py", line 173, in url
brp_1 |     return self.get_value(var, cast=urlparse.urlparse, default=default, parse_default=True)
brp_1 |   File "/usr/local/lib/python2.7/site-packages/environ/environ.py", line 250, in get_value
brp_1 |     raise ImproperlyConfigured(error_msg)
brp_1 | django.core.exceptions.ImproperlyConfigured: Set the REDIS_URL environment variable
brp_1 | Unknown command: 'migrate'
brp_1 | Type 'manage.py help' for usage.
brp_1 | Unknown command: 'collectstatic'
brp_1 | Type 'manage.py help' for usage.
brp_1 | [uwsgi-static] added mapping for /static => /opt/app/_site/static
brp_1 | [uwsgi-static] added mapping for /static => /usr/local/lib/python2.7/site-packages/django/contrib/admin/static
brp_1 | *** Starting uWSGI 2.0.11.2 (64bit) on [Tue Dec 15 10:53:00 2015] ***
brp_1 | compiled with version: 4.7.2 on 15 December 2015 10:49:11
brp_1 | os: Linux-4.2.0-18-generic #22-Ubuntu SMP Fri Nov 6 18:25:50 UTC 2015
brp_1 | nodename: b8228347632b
brp_1 | machine: x86_64
brp_1 | clock source: unix
brp_1 | pcre jit disabled
brp_1 | detected number of CPU cores: 8
brp_1 | current working directory: /opt/app
brp_1 | detected binary path: /usr/local/bin/uwsgi
brp_1 | uWSGI running as root, you can use --uid/--gid/--chroot options
brp_1 | *** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
brp_1 | chdir() to /opt/app/
brp_1 | your processes number limit is 1048576
brp_1 | your memory page size is 4096 bytes
brp_1 | detected max file descriptor number: 1048576
brp_1 | building mime-types dictionary from file /etc/mime.types...532 entry found
brp_1 | lock engine: pthread robust mutexes
brp_1 | thunder lock: disabled (you can enable it with --thunder-lock)
brp_1 | uwsgi socket 0 bound to TCP address 0.0.0.0:8000 fd 3
brp_1 | Python version: 2.7.8 (default, Dec  3 2014, 02:51:48)  [GCC 4.7.2]
brp_1 | Python main interpreter initialized at 0x751e00
brp_1 | python threads support enabled
brp_1 | your server socket listen backlog is limited to 100 connections
brp_1 | your mercy for graceful operations on workers is 60 seconds
brp_1 | mapped 304320 bytes (297 KB) for 2 cores
brp_1 | *** Operational MODE: preforking ***
brp_1 | WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x751e00 pid: 1 (default app)
brp_1 | *** uWSGI is running in multiple interpreter mode ***
brp_1 | spawned uWSGI master process (pid: 1)
brp_1 | spawned uWSGI worker 1 (pid: 12, cores: 1)
brp_1 | spawned uWSGI worker 2 (pid: 13, cores: 1)
````

**Comment by tjrivera** [comment]
thanks @ludovicc!
